export const GET_INVOICES_ACTION = "GET_INVOICES_ACTION";
export const GET_VENDORS_ACTION = "GET_VENDORS_ACTION";
export const GET_CONFIG_ACTION = "GET_CONFIG_ACTION";
export const ADJUST_CREDIT_ACTION = "ADJUST_CREDIT_ACTION";
export const ADJUST_BALANCE_ACTION = "ADJUST_BALANCE_ACTION";
